export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/api/auth/login/',
    REFRESH: '/api/auth/refresh/',
    LOGOUT: '/api/auth/logout/',
    PROFILE: '/api/auth/profile/',
    CHANGE_PASSWORD: '/api/auth/change-password/',
  },
  DASHBOARD: {
    SUPER_ADMIN: '/api/v1/dashboard/super-admin/',
  },
  HEALTH: '/api/v1/health/',
  REGISTER: '/api/v1/accounts/register/',
  ORGANIZATIONS: {
    LIST: '/api/v1/organizations/',
    DETAIL: (id) => `/api/v1/organizations/${id}/`,
    ACTIVATE: (id) => `/api/v1/organizations/${id}/activate/`,
    DEACTIVATE: (id) => `/api/v1/organizations/${id}/deactivate/`,
  },
  MEMBERSHIPS: {
    LIST: '/api/v1/memberships/',
    DETAIL: (id) => `/api/v1/memberships/${id}/`,
  },
  SCHOOLS: {
    LIST: '/api/v1/schools/',
    DETAIL: (id) => `/api/v1/schools/${id}/`,
  },
  ACADEMIC_YEARS: {
    LIST: '/api/v1/academic-years/',
    DETAIL: (id) => `/api/v1/academic-years/${id}/`,
  },
  USERS: {
    LIST: '/api/v1/users/',
    DETAIL: (id) => `/api/v1/users/${id}/`,
    ACTIVATE: (id) => `/api/v1/users/${id}/activate/`,
    DEACTIVATE: (id) => `/api/v1/users/${id}/deactivate/`,
    RESET_PASSWORD: (id) => `/api/v1/users/${id}/reset-password/`,
    BULK_ACTION: '/api/v1/users/bulk-action/',
    EXPORT: '/api/v1/users/export/',
  },
  ROLES: {
    LIST: '/api/v1/roles/',
    DETAIL: (id) => `/api/v1/roles/${id}/`,
    PERMISSIONS: (id) => `/api/v1/roles/${id}/permissions/`,
    ASSIGN_PERMISSIONS: (id) => `/api/v1/roles/${id}/permissions/assign/`,
    REMOVE_PERMISSIONS: (id) => `/api/v1/roles/${id}/permissions/remove/`,
    SYNC_PERMISSIONS: (id) => `/api/v1/roles/${id}/permissions/sync/`,
    MENUS: (id) => `/api/v1/roles/${id}/menus/`,
    ASSIGN_MENUS: (id) => `/api/v1/roles/${id}/menus/assign/`,
    REMOVE_MENUS: (id) => `/api/v1/roles/${id}/menus/remove/`,
    SYNC_MENUS: (id) => `/api/v1/roles/${id}/menus/sync/`,
  },
  PERMISSIONS: {
    LIST: '/api/v1/permissions/',
    DETAIL: (id) => `/api/v1/permissions/${id}/`,
    MATRIX: '/api/v1/permissions/matrix/',
  },
  USER_ROLES: {
    LIST: '/api/v1/user-roles/',
    DETAIL: (id) => `/api/v1/user-roles/${id}/`,
  },
  MODULES: {
    LIST: '/api/v1/modules/',
    DETAIL: (id) => `/api/v1/modules/${id}/`,
    REORDER: '/api/v1/modules/reorder/',
  },
  MENUS: {
    LIST: '/api/v1/menus/',
    DETAIL: (id) => `/api/v1/menus/${id}/`,
    MY_MENUS: '/api/v1/menus/my-menus/',
    TREE: '/api/v1/menus/tree/',
    REORDER: '/api/v1/menus/reorder/',
  },
  MASTERS: {
    COUNTRIES: '/api/v1/masters/countries/',
    STATES: '/api/v1/masters/states/',
    CITIES: '/api/v1/masters/cities/',
    BOARDS: '/api/v1/masters/boards/',
    CLASSES: '/api/v1/masters/classes/',
    SECTIONS: '/api/v1/masters/sections/',
    SUBJECTS: '/api/v1/masters/subjects/',
    DEPARTMENTS: '/api/v1/masters/departments/',
    DESIGNATIONS: '/api/v1/masters/designations/',
    CATEGORIES: '/api/v1/masters/categories/',
  },
  AUDIT_LOGS: {
    LIST: '/api/v1/audit-logs/',
    DETAIL: (id) => `/api/v1/audit-logs/${id}/`,
    FILTER_OPTIONS: '/api/v1/audit-logs/filter-options/',
  },
  SETTINGS: {
    SECTION: (section) => `/api/v1/settings/${section}/`,
  },
  NOTIFICATIONS: {
    LIST: '/api/v1/notifications/',
    DETAIL: (id) => `/api/v1/notifications/${id}/`,
    MARK_READ: (id) => `/api/v1/notifications/${id}/mark-read/`,
    MARK_ALL_READ: '/api/v1/notifications/mark-all-read/',
    UNREAD_COUNT: '/api/v1/notifications/unread-count/',
  },
  NEXUS_MAIL: {
    SEND: '/api/v1/nexus-mail/send/',
  },
}
