export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/api/auth/login/',
    REFRESH: '/api/auth/refresh/',
    LOGOUT: '/api/auth/logout/',
    PROFILE: '/api/auth/profile/',
    CHANGE_PASSWORD: '/api/auth/change-password/',
  },
  DASHBOARD: {
    SUPER_ADMIN: '/api/v1/dashboard/super-admin/',
    SCHOOL_ADMIN: '/api/v1/dashboard/school-admin/',
  },
  HEALTH: '/api/v1/health/',
  REGISTER: '/api/v1/accounts/register/',
  ORGANIZATIONS: {
    LIST: '/api/v1/organizations/',
    DETAIL: (id) => `/api/v1/organizations/${id}/`,
    ACTIVATE: (id) => `/api/v1/organizations/${id}/activate/`,
    DEACTIVATE: (id) => `/api/v1/organizations/${id}/deactivate/`,
  },
  MEMBERSHIPS: {
    LIST: '/api/v1/memberships/',
    DETAIL: (id) => `/api/v1/memberships/${id}/`,
  },
  SCHOOLS: {
    LIST: '/api/v1/schools/',
    DETAIL: (id) => `/api/v1/schools/${id}/`,
    PROFILE: (id) => `/api/v1/schools/${id}/profile/`,
    PROFILE_REGENERATE_QR: (id) => `/api/v1/schools/${id}/profile/regenerate-qr/`,
  },
  SCHOOL_PROFILE: '/api/v1/school-profile/',
  ACADEMIC_YEARS: {
    LIST: '/api/v1/academic-years/',
    DETAIL: (id) => `/api/v1/academic-years/${id}/`,
  },
  ACADEMICS: {
    TERMS: '/api/v1/academics/terms/',
    CLASS_SECTIONS: '/api/v1/academics/class-sections/',
    CURRICULUMS: '/api/v1/academics/curriculums/',
    CURRICULUM_SUBJECTS: '/api/v1/academics/curriculum-subjects/',
    ELECTIVE_SUBJECTS: '/api/v1/academics/elective-subjects/',
    CLASS_TEACHERS: '/api/v1/academics/class-teachers/',
    CALENDAR_EVENTS: '/api/v1/academics/calendar-events/',
    CLASS_TIMINGS: '/api/v1/academics/class-timings/',
    PERIODS: '/api/v1/academics/periods/',
    WORKING_DAYS: '/api/v1/academics/working-days/',
    HOLIDAYS: '/api/v1/academics/holidays/',
  },
  USERS: {
    LIST: '/api/v1/users/',
    DETAIL: (id) => `/api/v1/users/${id}/`,
    ACTIVATE: (id) => `/api/v1/users/${id}/activate/`,
    DEACTIVATE: (id) => `/api/v1/users/${id}/deactivate/`,
    RESET_PASSWORD: (id) => `/api/v1/users/${id}/reset-password/`,
    BULK_ACTION: '/api/v1/users/bulk-action/',
    EXPORT: '/api/v1/users/export/',
  },
  SCHOOL_USERS: {
    LIST: '/api/v1/school-users/',
    DETAIL: (id) => `/api/v1/school-users/${id}/`,
    ACTIVATE: (id) => `/api/v1/school-users/${id}/activate/`,
    DEACTIVATE: (id) => `/api/v1/school-users/${id}/deactivate/`,
    RESET_PASSWORD: (id) => `/api/v1/school-users/${id}/reset-password/`,
    SEND_CREDENTIALS: (id) => `/api/v1/school-users/${id}/send-credentials/`,
    LOGIN_HISTORY: (id) => `/api/v1/school-users/${id}/login-history/`,
    DEVICES: (id) => `/api/v1/school-users/${id}/devices/`,
    STAFF_ROLES: '/api/v1/school-users/staff-roles/',
  },
  ADMISSIONS: {
    LEADS: '/api/v1/admissions/leads/',
    LEAD_DETAIL: (id) => `/api/v1/admissions/leads/${id}/`,
    LEAD_CONVERT: (id) => `/api/v1/admissions/leads/${id}/convert/`,
    LEAD_FOLLOW_UPS: (id) => `/api/v1/admissions/leads/${id}/follow-ups/`,
    APPLICATIONS: '/api/v1/admissions/applications/',
    APPLICATION_DETAIL: (id) => `/api/v1/admissions/applications/${id}/`,
    PIPELINE_STATS: '/api/v1/admissions/applications/pipeline-stats/',
    SUBMIT_APPLICATION: (id) => `/api/v1/admissions/applications/${id}/submit-application/`,
    UPLOAD_DOCUMENT: (id) => `/api/v1/admissions/applications/${id}/upload-document/`,
    VERIFY_DOCUMENTS: (id) => `/api/v1/admissions/applications/${id}/verify-documents/`,
    ENTRANCE_TEST: (id) => `/api/v1/admissions/applications/${id}/entrance-test/`,
    INTERVIEW: (id) => `/api/v1/admissions/applications/${id}/interview/`,
    SUBMIT_APPROVAL: (id) => `/api/v1/admissions/applications/${id}/submit-approval/`,
    APPROVE: (id) => `/api/v1/admissions/applications/${id}/approve/`,
    REJECT: (id) => `/api/v1/admissions/applications/${id}/reject/`,
    COLLECT_FEE: (id) => `/api/v1/admissions/applications/${id}/collect-fee/`,
    CONFIRM: (id) => `/api/v1/admissions/applications/${id}/confirm/`,
    ENROLL: (id) => `/api/v1/admissions/applications/${id}/enroll/`,
    RECEIPT: (id) => `/api/v1/admissions/applications/${id}/receipt/`,
    FOLLOW_UPS: (id) => `/api/v1/admissions/applications/${id}/follow-ups/`,
  },
  STUDENTS: {
    LIST: '/api/v1/students/',
    DETAIL: (id) => `/api/v1/students/${id}/`,
    BULK_IMPORT: '/api/v1/students/bulk-import/',
    EXPORT: '/api/v1/students/export/',
    REGENERATE_QR: (id) => `/api/v1/students/${id}/regenerate-qr/`,
    ID_CARD: (id) => `/api/v1/students/${id}/id-card/`,
    UPDATE_STATUS: (id) => `/api/v1/students/${id}/update-status/`,
    TRANSPORT: (id) => `/api/v1/students/${id}/transport/`,
    HOSTEL: (id) => `/api/v1/students/${id}/hostel/`,
    MEDICAL: (id) => `/api/v1/students/${id}/medical/`,
    UPLOAD_DOCUMENT: (id) => `/api/v1/students/${id}/upload-document/`,
    ACHIEVEMENTS: (id) => `/api/v1/students/${id}/achievements/`,
    DISCIPLINE: (id) => `/api/v1/students/${id}/discipline/`,
    SIBLINGS: (id) => `/api/v1/students/${id}/siblings/`,
    PROMOTE: (id) => `/api/v1/students/${id}/promote/`,
  },
  TEACHERS: {
    LIST: '/api/v1/teachers/',
    DETAIL: (id) => `/api/v1/teachers/${id}/`,
    EXPORT: '/api/v1/teachers/export/',
    SEND_CREDENTIALS: (id) => `/api/v1/teachers/${id}/send-credentials/`,
    QUALIFICATIONS: (id) => `/api/v1/teachers/${id}/qualifications/`,
    EXPERIENCE: (id) => `/api/v1/teachers/${id}/experience/`,
    ASSIGN_SUBJECT: (id) => `/api/v1/teachers/${id}/assign-subject/`,
    CLASS_TEACHER: (id) => `/api/v1/teachers/${id}/class-teacher/`,
    ATTENDANCE: (id) => `/api/v1/teachers/${id}/attendance/`,
    LEAVE: (id) => `/api/v1/teachers/${id}/leave/`,
    APPROVE_LEAVE: (id, leaveId) => `/api/v1/teachers/${id}/leave/${leaveId}/approve/`,
    PAYROLL: (id) => `/api/v1/teachers/${id}/payroll/`,
    UPLOAD_DOCUMENT: (id) => `/api/v1/teachers/${id}/upload-document/`,
    CERTIFICATES: (id) => `/api/v1/teachers/${id}/certificates/`,
    TIMETABLE: (id) => `/api/v1/teachers/${id}/timetable/`,
    LESSON_PLANS: (id) => `/api/v1/teachers/${id}/lesson-plans/`,
    HOMEWORK: (id) => `/api/v1/teachers/${id}/homework/`,
    ONLINE_CLASSES: (id) => `/api/v1/teachers/${id}/online-classes/`,
    PERFORMANCE_REVIEWS: (id) => `/api/v1/teachers/${id}/performance-reviews/`,
  },
  STAFF: {
    LIST: '/api/v1/staff/',
    DETAIL: (id) => `/api/v1/staff/${id}/`,
    EXPORT: '/api/v1/staff/export/',
    SEND_CREDENTIALS: (id) => `/api/v1/staff/${id}/send-credentials/`,
    RESET_PASSWORD: (id) => `/api/v1/staff/${id}/reset-password/`,
    EMERGENCY_CONTACT: (id) => `/api/v1/staff/${id}/emergency-contact/`,
    EXPERIENCE: (id) => `/api/v1/staff/${id}/experience/`,
    SKILLS: (id) => `/api/v1/staff/${id}/skills/`,
    SHIFT: (id) => `/api/v1/staff/${id}/shift/`,
    ATTENDANCE: (id) => `/api/v1/staff/${id}/attendance/`,
    LEAVE: (id) => `/api/v1/staff/${id}/leave/`,
    APPROVE_LEAVE: (id, leaveId) => `/api/v1/staff/${id}/leave/${leaveId}/approve/`,
    PAYROLL: (id) => `/api/v1/staff/${id}/payroll/`,
    UPLOAD_DOCUMENT: (id) => `/api/v1/staff/${id}/upload-document/`,
    AUDIT_LOGS: (id) => `/api/v1/staff/${id}/audit-logs/`,
  },
  PARENTS: {
    LIST: '/api/v1/parents/',
    DETAIL: (id) => `/api/v1/parents/${id}/`,
    EXPORT: '/api/v1/parents/export/',
    SEND_CREDENTIALS: (id) => `/api/v1/parents/${id}/send-credentials/`,
    RESET_PASSWORD: (id) => `/api/v1/parents/${id}/reset-password/`,
    LINK_STUDENT: (id) => `/api/v1/parents/${id}/link-student/`,
    UNLINK_STUDENT: (id) => `/api/v1/parents/${id}/unlink-student/`,
    COMMUNICATION: (id) => `/api/v1/parents/${id}/communication/`,
    EMERGENCY_CONTACT: (id) => `/api/v1/parents/${id}/emergency-contact/`,
    GUARDIAN: (id) => `/api/v1/parents/${id}/guardian/`,
    MOBILE_APP_ACCESS: (id) => `/api/v1/parents/${id}/mobile-app-access/`,
  },
  COMMUNICATIONS: {
    TEMPLATES: '/api/v1/communications/templates/',
    TEMPLATE_DETAIL: (id) => `/api/v1/communications/templates/${id}/`,
    MESSAGES: '/api/v1/communications/messages/',
    MESSAGE_DETAIL: (id) => `/api/v1/communications/messages/${id}/`,
    PREVIEW_AUDIENCE: '/api/v1/communications/messages/preview-audience/',
    SEND: (id) => `/api/v1/communications/messages/${id}/send/`,
    SCHEDULE: (id) => `/api/v1/communications/messages/${id}/schedule/`,
    CANCEL: (id) => `/api/v1/communications/messages/${id}/cancel/`,
    DELIVERY_REPORT: (id) => `/api/v1/communications/messages/${id}/delivery-report/`,
    READ_RECEIPTS: (id) => `/api/v1/communications/messages/${id}/read-receipts/`,
    PROCESS_SCHEDULED: '/api/v1/communications/messages/process-scheduled/',
    DELIVERIES: '/api/v1/communications/deliveries/',
    DELIVERY_DETAIL: (id) => `/api/v1/communications/deliveries/${id}/`,
    MARK_READ: (id) => `/api/v1/communications/deliveries/${id}/mark-read/`,
  },
  ROLES: {
    LIST: '/api/v1/roles/',
    DETAIL: (id) => `/api/v1/roles/${id}/`,
    PERMISSIONS: (id) => `/api/v1/roles/${id}/permissions/`,
    ASSIGN_PERMISSIONS: (id) => `/api/v1/roles/${id}/permissions/assign/`,
    REMOVE_PERMISSIONS: (id) => `/api/v1/roles/${id}/permissions/remove/`,
    SYNC_PERMISSIONS: (id) => `/api/v1/roles/${id}/permissions/sync/`,
    MENUS: (id) => `/api/v1/roles/${id}/menus/`,
    ASSIGN_MENUS: (id) => `/api/v1/roles/${id}/menus/assign/`,
    REMOVE_MENUS: (id) => `/api/v1/roles/${id}/menus/remove/`,
    SYNC_MENUS: (id) => `/api/v1/roles/${id}/menus/sync/`,
  },
  PERMISSIONS: {
    LIST: '/api/v1/permissions/',
    DETAIL: (id) => `/api/v1/permissions/${id}/`,
    MATRIX: '/api/v1/permissions/matrix/',
  },
  USER_ROLES: {
    LIST: '/api/v1/user-roles/',
    DETAIL: (id) => `/api/v1/user-roles/${id}/`,
  },
  MODULES: {
    LIST: '/api/v1/modules/',
    DETAIL: (id) => `/api/v1/modules/${id}/`,
    REORDER: '/api/v1/modules/reorder/',
  },
  MENUS: {
    LIST: '/api/v1/menus/',
    DETAIL: (id) => `/api/v1/menus/${id}/`,
    MY_MENUS: '/api/v1/menus/my-menus/',
    TREE: '/api/v1/menus/tree/',
    REORDER: '/api/v1/menus/reorder/',
  },
  MASTERS: {
    COUNTRIES: '/api/v1/masters/countries/',
    STATES: '/api/v1/masters/states/',
    CITIES: '/api/v1/masters/cities/',
    BOARDS: '/api/v1/masters/boards/',
    CLASSES: '/api/v1/masters/classes/',
    SECTIONS: '/api/v1/masters/sections/',
    SUBJECTS: '/api/v1/masters/subjects/',
    STREAMS: '/api/v1/masters/streams/',
    SUBJECT_GROUPS: '/api/v1/masters/subject-groups/',
    DEPARTMENTS: '/api/v1/masters/departments/',
    DESIGNATIONS: '/api/v1/masters/designations/',
    CATEGORIES: '/api/v1/masters/categories/',
  },
  SCHOOL_MASTERS: {
    TYPES: '/api/v1/school-masters/types/',
    LIST: (type) => `/api/v1/school-masters/${type}/`,
    DETAIL: (type, id) => `/api/v1/school-masters/${type}/${id}/`,
    BULK_IMPORT: (type) => `/api/v1/school-masters/${type}/bulk-import/`,
    EXPORT: (type) => `/api/v1/school-masters/${type}/export/`,
  },
  AUDIT_LOGS: {
    LIST: '/api/v1/audit-logs/',
    DETAIL: (id) => `/api/v1/audit-logs/${id}/`,
    FILTER_OPTIONS: '/api/v1/audit-logs/filter-options/',
  },
  SETTINGS: {
    SECTION: (section) => `/api/v1/settings/${section}/`,
  },
  SCHOOL_SETTINGS: {
    SECTIONS: '/api/v1/school-settings/sections/',
    ALL: '/api/v1/school-settings/all/',
    SECTION: (section) => `/api/v1/school-settings/${section}/`,
    PREVIEW_NUMBER: '/api/v1/school-settings/preview-number/',
  },
  NOTIFICATIONS: {
    LIST: '/api/v1/notifications/',
    DETAIL: (id) => `/api/v1/notifications/${id}/`,
    MARK_READ: (id) => `/api/v1/notifications/${id}/mark-read/`,
    MARK_ALL_READ: '/api/v1/notifications/mark-all-read/',
    UNREAD_COUNT: '/api/v1/notifications/unread-count/',
  },
  NEXUS_MAIL: {
    SEND: '/api/v1/nexus-mail/send/',
  },
}
