import { DESCRIPTION_COLUMN } from '@/config/masterColumns'
import { SUBJECT_TYPE_OPTIONS } from '@/config/masterFieldChoices'

export const MASTER_DEFINITIONS = {
  countries: {
    key: 'countries',
    label: 'Country',
    labelPlural: 'Countries',
    serviceKey: 'countries',
    superAdminOnly: true,
    fields: [
      { name: 'organization_id', label: 'Organization', type: 'text', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', required: true, readOnlyOnEdit: true },
      { name: 'sequence', label: 'Sequence', type: 'number' },
      { name: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    columns: [
      { accessorKey: 'name', header: 'Name' },
      { accessorKey: 'code', header: 'Code' },
      { accessorKey: 'sequence', header: 'Seq' },
      { accessorKey: 'is_active', header: 'Status', cell: ({ getValue }) => (getValue() ? 'Active' : 'Inactive') },
    ],
  },
  states: {
    key: 'states',
    label: 'State',
    labelPlural: 'States',
    serviceKey: 'states',
    superAdminOnly: true,
    fields: [
      { name: 'organization_id', label: 'Organization', type: 'text', required: true },
      { name: 'country', label: 'Country', type: 'text', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', required: true, readOnlyOnEdit: true },
      { name: 'sequence', label: 'Sequence', type: 'number' },
      { name: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    columns: [
      { accessorKey: 'name', header: 'Name' },
      { accessorKey: 'code', header: 'Code' },
      { accessorKey: 'sequence', header: 'Seq' },
      { accessorKey: 'country_name', header: 'Country' },
      { accessorKey: 'is_active', header: 'Status', cell: ({ getValue }) => (getValue() ? 'Active' : 'Inactive') },
    ],
  },
  cities: {
    key: 'cities',
    label: 'City',
    labelPlural: 'Cities',
    serviceKey: 'cities',
    superAdminOnly: true,
    fields: [
      { name: 'organization_id', label: 'Organization', type: 'text', required: true },
      { name: 'state', label: 'State', type: 'text', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', required: true, readOnlyOnEdit: true },
      { name: 'sequence', label: 'Sequence', type: 'number' },
      { name: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    columns: [
      { accessorKey: 'name', header: 'Name' },
      { accessorKey: 'code', header: 'Code' },
      { accessorKey: 'sequence', header: 'Seq' },
      { accessorKey: 'state_name', header: 'State' },
      { accessorKey: 'is_active', header: 'Status', cell: ({ getValue }) => (getValue() ? 'Active' : 'Inactive') },
    ],
  },
  boards: {
    key: 'boards',
    label: 'Board',
    labelPlural: 'Boards',
    serviceKey: 'boards',
    fields: [
      { name: 'organization_id', label: 'Organization', type: 'text', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', required: true, readOnlyOnEdit: true },
      { name: 'sequence', label: 'Sequence', type: 'number' },
      { name: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    columns: [
      { accessorKey: 'name', header: 'Name' },
      { accessorKey: 'code', header: 'Code' },
      { accessorKey: 'sequence', header: 'Seq' },
      { accessorKey: 'is_active', header: 'Status', cell: ({ getValue }) => (getValue() ? 'Active' : 'Inactive') },
    ],
  },
  classes: {
    key: 'classes',
    label: 'Class',
    labelPlural: 'Classes',
    serviceKey: 'classes',
    fields: [
      { name: 'organization_id', label: 'Organization', type: 'text' },
      { name: 'school_id', label: 'School', type: 'text' },
      { name: 'board', label: 'Board', type: 'text' },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', required: true, readOnlyOnEdit: true },
      { name: 'sequence', label: 'Sequence', type: 'number' },
      { name: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    columns: [
      { accessorKey: 'name', header: 'Name' },
      { accessorKey: 'code', header: 'Code' },
      { accessorKey: 'sequence', header: 'Seq' },
      { accessorKey: 'board_name', header: 'Board' },
    ],
  },
  sections: {
    key: 'sections',
    label: 'Section',
    labelPlural: 'Sections',
    serviceKey: 'sections',
    fields: [
      { name: 'organization_id', label: 'Organization', type: 'text' },
      { name: 'school_id', label: 'School', type: 'text' },
      { name: 'school_class', label: 'Class', type: 'text' },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', required: true, readOnlyOnEdit: true },
      { name: 'capacity', label: 'Capacity', type: 'number' },
      { name: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    columns: [
      { accessorKey: 'name', header: 'Name' },
      { accessorKey: 'code', header: 'Code' },
      { accessorKey: 'sequence', header: 'Seq' },
      { accessorKey: 'class_name', header: 'Class' },
      { accessorKey: 'capacity', header: 'Capacity' },
    ],
  },
  subjects: {
    key: 'subjects',
    label: 'Subject',
    labelPlural: 'Subjects',
    serviceKey: 'subjects',
    schoolScoped: true,
    fields: [
      { name: 'organization_id', label: 'Organization', type: 'text', required: true },
      { name: 'school_id', label: 'School', type: 'text', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', required: true, readOnlyOnEdit: true },
      { name: 'subject_type', label: 'Subject Type', type: 'select', options: SUBJECT_TYPE_OPTIONS },
      { name: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    columns: [
      { accessorKey: 'name', header: 'Name' },
      { accessorKey: 'code', header: 'Code' },
      DESCRIPTION_COLUMN,
      { accessorKey: 'sequence', header: 'Seq' },
      { accessorKey: 'subject_type', header: 'Type' },
    ],
  },
  streams: {
    key: 'streams',
    label: 'Stream',
    labelPlural: 'Streams',
    serviceKey: 'streams',
    schoolScoped: true,
    fields: [
      { name: 'organization_id', label: 'Organization', type: 'text', required: true },
      { name: 'school_id', label: 'School', type: 'text', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', required: true, readOnlyOnEdit: true },
      { name: 'sequence', label: 'Sequence', type: 'number' },
      { name: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    columns: [
      { accessorKey: 'name', header: 'Name' },
      { accessorKey: 'code', header: 'Code' },
      DESCRIPTION_COLUMN,
      { accessorKey: 'sequence', header: 'Seq' },
    ],
  },
  'subject-groups': {
    key: 'subject-groups',
    label: 'Subject Group',
    labelPlural: 'Subject Groups',
    serviceKey: 'subjectGroups',
    schoolScoped: true,
    fields: [
      { name: 'organization_id', label: 'Organization', type: 'text', required: true },
      { name: 'school_id', label: 'School', type: 'text', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', required: true, readOnlyOnEdit: true },
      { name: 'sequence', label: 'Sequence', type: 'number' },
      { name: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    columns: [
      { accessorKey: 'name', header: 'Name' },
      { accessorKey: 'code', header: 'Code' },
      DESCRIPTION_COLUMN,
      { accessorKey: 'sequence', header: 'Seq' },
    ],
  },
  departments: {
    key: 'departments',
    label: 'Department',
    labelPlural: 'Departments',
    serviceKey: 'departments',
    schoolScoped: true,
    fields: [
      { name: 'organization_id', label: 'Organization', type: 'text', required: true },
      { name: 'school_id', label: 'School', type: 'text', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', required: true, readOnlyOnEdit: true },
      { name: 'sequence', label: 'Sequence', type: 'number' },
      { name: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    columns: [
      { accessorKey: 'name', header: 'Name' },
      { accessorKey: 'code', header: 'Code' },
      DESCRIPTION_COLUMN,
      { accessorKey: 'sequence', header: 'Seq' },
    ],
  },
  designations: {
    key: 'designations',
    label: 'Designation',
    labelPlural: 'Designations',
    serviceKey: 'designations',
    schoolScoped: true,
    fields: [
      { name: 'organization_id', label: 'Organization', type: 'text', required: true },
      { name: 'school_id', label: 'School', type: 'text', required: true },
      { name: 'department', label: 'Department', type: 'text' },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', required: true, readOnlyOnEdit: true },
      { name: 'sequence', label: 'Sequence', type: 'number' },
      { name: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    columns: [
      { accessorKey: 'name', header: 'Name' },
      { accessorKey: 'code', header: 'Code' },
      DESCRIPTION_COLUMN,
      { accessorKey: 'sequence', header: 'Seq' },
      { accessorKey: 'department_name', header: 'Department' },
    ],
  },
  categories: {
    key: 'categories',
    label: 'Category',
    labelPlural: 'Categories',
    serviceKey: 'categories',
    fields: [
      { name: 'organization_id', label: 'Organization', type: 'text', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', required: true, readOnlyOnEdit: true },
      { name: 'category_type', label: 'Category Type', type: 'text', placeholder: 'e.g. library, payroll, fee' },
      { name: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    columns: [
      { accessorKey: 'name', header: 'Name' },
      { accessorKey: 'code', header: 'Code' },
      { accessorKey: 'sequence', header: 'Seq' },
      { accessorKey: 'category_type', header: 'Type' },
    ],
  },
  'academic-years': {
    key: 'academic-years',
    label: 'Academic Year',
    labelPlural: 'Academic Years',
    serviceKey: 'academicYears',
    fields: [
      { name: 'organization_id', label: 'Organization', type: 'text', required: true },
      { name: 'school', label: 'School', type: 'text', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'start_date', label: 'Start Date', type: 'date', required: true },
      { name: 'end_date', label: 'End Date', type: 'date', required: true },
      { name: 'is_current', label: 'Current Year', type: 'checkbox' },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    columns: [
      { accessorKey: 'name', header: 'Name' },
      { accessorKey: 'school_name', header: 'School' },
      { accessorKey: 'start_date', header: 'Start' },
      { accessorKey: 'end_date', header: 'End' },
      { accessorKey: 'is_current', header: 'Current', cell: ({ getValue }) => (getValue() ? 'Yes' : 'No') },
    ],
  },
}
