export const STUDENT_BULK_IMPORT_COLUMNS = [
  { key: 'first_name', header: 'First Name', required: true },
  { key: 'last_name', header: 'Last Name' },
  { key: 'middle_name', header: 'Middle Name' },
  { key: 'mobile_number', header: 'Mobile', hint: 'required if Email empty' },
  { key: 'email', header: 'Email', hint: 'required if Mobile empty' },
  { key: 'admission_number', header: 'Admission Number', hint: 'auto-generated if blank' },
  { key: 'roll_number', header: 'Roll Number' },
  { key: 'date_of_birth', header: 'Date of Birth', type: 'date' },
  { key: 'gender', header: 'Gender' },
  { key: 'blood_group', header: 'Blood Group' },
  { key: 'religion', header: 'Religion' },
  { key: 'nationality', header: 'Nationality' },
  { key: 'aadhaar_number', header: 'Aadhaar Number' },
  { key: 'emis_number', header: 'EMIS Number' },
  { key: 'class_name', header: 'Class', hint: 'must match active class' },
  { key: 'section_name', header: 'Section', hint: 'must match active section' },
  { key: 'address', header: 'Address' },
  { key: 'city', header: 'City' },
  { key: 'state', header: 'State' },
  { key: 'pincode', header: 'Pincode' },
  { key: 'country', header: 'Country' },
  { key: 'permanent_address', header: 'Permanent Address' },
  { key: 'current_address', header: 'Current Address' },
  { key: 'previous_school', header: 'Previous School' },
  { key: 'previous_school_board', header: 'Previous School Board' },
  { key: 'previous_class', header: 'Previous Class' },
  { key: 'emergency_contact_name', header: 'Emergency Contact Name' },
  { key: 'emergency_contact_phone', header: 'Emergency Contact Phone' },
  { key: 'emergency_contact_relation', header: 'Emergency Contact Relation' },
  { key: 'special_needs', header: 'Special Needs' },
  { key: 'notes', header: 'Notes' },
  { key: 'father_name', header: 'Father Name' },
  { key: 'father_mobile', header: 'Father Mobile' },
  { key: 'father_email', header: 'Father Email' },
  { key: 'father_occupation', header: 'Father Occupation' },
  { key: 'father_qualification', header: 'Father Qualification' },
  { key: 'father_company', header: 'Father Company' },
  { key: 'father_annual_income', header: 'Father Annual Income' },
  { key: 'mother_name', header: 'Mother Name' },
  { key: 'mother_mobile', header: 'Mother Mobile' },
  { key: 'mother_email', header: 'Mother Email' },
  { key: 'mother_occupation', header: 'Mother Occupation' },
  { key: 'mother_qualification', header: 'Mother Qualification' },
  { key: 'mother_company', header: 'Mother Company' },
  { key: 'mother_annual_income', header: 'Mother Annual Income' },
  { key: 'guardian_name', header: 'Guardian Name' },
  { key: 'guardian_mobile', header: 'Guardian Mobile' },
  { key: 'guardian_email', header: 'Guardian Email' },
  { key: 'guardian_relationship', header: 'Guardian Relationship' },
  { key: 'transport_required', header: 'Transport Required', hint: 'yes/no' },
  { key: 'transport_mode', header: 'Transport Mode' },
  { key: 'route_name', header: 'Route Name' },
  { key: 'route_code', header: 'Route Code' },
  { key: 'stop_name', header: 'Stop Name' },
  { key: 'pickup_point', header: 'Pickup Point' },
  { key: 'drop_point', header: 'Drop Point' },
  { key: 'vehicle_number', header: 'Vehicle Number' },
  { key: 'driver_name', header: 'Driver Name' },
  { key: 'driver_phone', header: 'Driver Phone' },
  { key: 'hostel_required', header: 'Hostel Required', hint: 'yes/no' },
  { key: 'hostel_name', header: 'Hostel Name' },
  { key: 'building', header: 'Hostel Building' },
  { key: 'block', header: 'Hostel Block' },
  { key: 'floor', header: 'Hostel Floor' },
  { key: 'room_number', header: 'Room Number' },
  { key: 'bed_number', header: 'Bed Number' },
  { key: 'mess_plan', header: 'Mess Plan' },
  { key: 'warden_name', header: 'Warden Name' },
  { key: 'warden_phone', header: 'Warden Phone' },
  { key: 'allergies', header: 'Allergies' },
  { key: 'chronic_conditions', header: 'Chronic Conditions' },
  { key: 'medications', header: 'Medications' },
  { key: 'doctor_name', header: 'Doctor Name' },
  { key: 'doctor_phone', header: 'Doctor Phone' },
  { key: 'hospital', header: 'Hospital' },
  { key: 'health_notes', header: 'Health Notes' },
  { key: 'emergency_instructions', header: 'Emergency Instructions' },
]

export const STUDENT_BULK_IMPORT_EXAMPLE_ROWS = [
  {
    'First Name': 'Rahul',
    'Last Name': 'Sharma',
    'Middle Name': 'Kumar',
    Mobile: '9876543210',
    Email: '',
    'Admission Number': '',
    'Roll Number': '101',
    'Date of Birth': '15-04-2012',
    Gender: 'male',
    'Blood Group': 'B+',
    Religion: 'Hindu',
    Nationality: 'Indian',
    'Aadhaar Number': '',
    'EMIS Number': '',
    Class: 'Grade 1',
    Section: 'A',
    Address: '12 MG Road',
    City: 'Chennai',
    State: 'Tamil Nadu',
    Pincode: '600001',
    Country: 'India',
    'Permanent Address': '',
    'Current Address': '',
    'Previous School': 'ABC Primary School',
    'Previous School Board': 'CBSE',
    'Previous Class': '4',
    'Emergency Contact Name': 'Rajesh Sharma',
    'Emergency Contact Phone': '9876500001',
    'Emergency Contact Relation': 'Father',
    'Special Needs': '',
    Notes: '',
    'Father Name': 'Rajesh Sharma',
    'Father Mobile': '9876500001',
    'Father Email': 'rajesh@example.com',
    'Father Occupation': 'Engineer',
    'Father Qualification': 'B.E.',
    'Father Company': 'Tech Corp',
    'Father Annual Income': '1200000',
    'Mother Name': 'Priya Sharma',
    'Mother Mobile': '9876500002',
    'Mother Email': 'priya@example.com',
    'Mother Occupation': 'Teacher',
    'Mother Qualification': 'M.A.',
    'Mother Company': 'City School',
    'Mother Annual Income': '600000',
    'Guardian Name': '',
    'Guardian Mobile': '',
    'Guardian Email': '',
    'Guardian Relationship': '',
    'Transport Required': 'yes',
    'Transport Mode': 'school_bus',
    'Route Name': 'Route 12',
    'Route Code': 'R12',
    'Stop Name': 'MG Road Stop',
    'Pickup Point': 'Near Park',
    'Drop Point': 'School Gate',
    'Vehicle Number': '',
    'Driver Name': '',
    'Driver Phone': '',
    'Hostel Required': 'no',
    'Hostel Name': '',
    'Hostel Building': '',
    'Hostel Block': '',
    'Hostel Floor': '',
    'Room Number': '',
    'Bed Number': '',
    'Mess Plan': '',
    'Warden Name': '',
    'Warden Phone': '',
    Allergies: 'Peanuts',
    'Chronic Conditions': '',
    Medications: '',
    'Doctor Name': 'Dr. Mehta',
    'Doctor Phone': '9876500999',
    Hospital: 'City Hospital',
    'Health Notes': '',
    'Emergency Instructions': 'Use EpiPen if needed',
  },
]
